# Generated by Django 4.0 on 2021-12-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Packaging_Type",
            new_name="Packaging",
        ),
        migrations.RemoveField(
            model_name="product",
            name="packaging_type",
        ),
        migrations.AddField(
            model_name="product",
            name="packaging",
            field=models.ManyToManyField(to="products.Packaging"),
        ),
        migrations.AlterModelTable(
            name="packaging",
            table="packagings",
        ),
    ]
